version: '3'
services:
  stock-importer:
    build:
      context: .
      dockerfile: stock-importer/Dockerfile  
    container_name: stock-importer
    environment:
      - INFLUXDB_USER=${INFLUXDB_USER}  
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
     - influxdb

  tweet-importer:
    build:
      context: .
      dockerfile: tweet-importer/Dockerfile  
    container_name: tweet-importer
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
     - elasticsearch

  influxdb:
    build:
      context: .
      dockerfile: influxdb/Dockerfile  
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_USER=${INFLUXDB_USER}  
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
    
  elasticsearch:
    build:
      context: .
      dockerfile: elasticsearch/Dockerfile  
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "discovery.type=single-node"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
        

volumes:
  influxdb-data:
  elasticsearch-data:
