[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Shegy2106", email = "darko.segvic@gmail.com"},
]
dependencies = [
    "influxdb-client>=1.38.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "SPDX: MIT"}

